---
version: 0.1
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
retryOnFailure: false
runson: ${matrix.os}
cypress: true
maxRetries: 2
parallelism: 1
concurrency: 2
cacheKey: '{{ checksum "package.json" }}'
cacheDirectories:
  - node_modules
pre:
  - npm install
matrix:
   os: [linux]
   browser: ["chrome-104.0","chrome-105.0"]
   files: ["actions.spec.js", "aliasing.spec.js"]
testSuites: 
  - npx cypress run  --spec ./cypress/integration/$files --browser=$browser --headed --config video=false

mergeArtifacts: true

uploadArtefacts:
  - name: XmlReports
    path:
      - cypress/results/*

report: true
partialReports:
 location: cypress/results
 type: html
 frameworkName: cypress

cypressOps:
 Build: "Hyperexecute Cypress Sample Build"
 Tags: ["Hyperexecute","Cypress", "LINUX", "Matrix", "V9"]
 BuildTags: ["Hyperexecute-Cypress"]
post:
  - cat ./yaml/linux/.hyperexecute_autosplit.yaml

jobLabel: [cypress-v9, linux, matrix]