---
version: 0.1
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
retryOnFailure: true
runson: mac
cypress: true
maxRetries: 1
concurrency: 2
autosplit: true
cacheKey: '{{ checksum "package.json" }}'
cacheDirectories:
  - node_modules
pre:
  - npm install
testDiscovery:
  mode: static
  type: raw
  command: ls cypress/integration | sed -n 1,'10p'
  
mergeArtifacts: true

uploadArtefacts:
  - name: XmlReports
    path:
      - cypress/results/*

report: true
partialReports:
 location: cypress/results
 type: html
 frameworkName: cypress

testRunnerCommand: npx cypress run  --spec ./cypress/integration/$test --browser=chrome-95.0 --headed --config video=false
cypressOps:
 Build: "Hyperexecute Cypress Sample Build"
 Tags: ["Hyperexecute","Cypress", "MaCOS", "Autosplit", "V9"]
 BuildTags: ["Hyperexecute-Cypress"]
post:
  - cat ./yaml/mac/.hyperexecute_matrix.yaml


jobLabel: [cypress-v9, mac, autosplit]