---
version: 0.1
runson: mac

autosplit: true
concurrency: 2

cypress: true
cypressOps:
  Build: "Hyperexecute Cypress Sample Build"
  Tags: ["HYP-Cypress", "macOS", "Autosplit", "Accessibility"]
  BuildTags: ["HYP-Cypress-v9"]
  accessibility: true
  accessibilityWcagVersion: "wcag21a"
  accessibilityBestPractice: false  
  accessibilityNeedsReview: true

pre:
  - npm install
  - npm install cypress@9.6.1 --save-dev
  - npm i lambdatest-cypress-cli

testDiscovery:
  mode: static
  type: raw
  command: ls cypress/integration | sed -n 1,'10p'

testRunnerCommand: npx cypress run  --spec ./cypress/integration/$test --browser=chrome-latest --headed --config video=true

jobLabel: [cypress-v9, mac, autosplit]