---
version: 0.1
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
retryOnFailure: true
runson: win
cypress: true
maxRetries: 1
concurrency: 2
autosplit: true
# cacheKey: '{{ checksum "package.json" }}'
# cacheDirectories:
#   - node_modules
#   - cypressCache
env:
  CYPRESS_CACHE_FOLDER: cypressCache
testDiscovery:
  mode: static
  type: raw
  command: ls cypress/integration
testRunnerCommand: npx cypress run  --spec ./cypress/integration/$test --browser=chrome-95.0 --headed --config video=false
mergeArtifacts: true

uploadArtefacts:
  - name: XmlReports
    path:
      - cypress/results/*

report: true
partialReports:
 location: cypress/results
 type: html
 frameworkName: cypress

cypressOps:
 Build: "Hyperexecute Cypress Sample Build"
 Tags: ["Hyperexecute","Cypress", "Windows", "Autosplit", "V9"]
 BuildTags: ["Hyperexecute-Cypress"]
post:
  - cat ./yaml/win/.hyperexecute_matrix.yaml
pre:
  - npm install

jobLabel: [cypress-v9, win, autosplit]